[package]
name = "grpc-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.40", features = ["full"] }

[build-dependencies]
tonic-build = "0.12.0" 
